[package]
name = "blockchain"
version = "0.1.1"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }